Tracker:
  # first is w, x, y, z similar with order in Eigen::Quaternion();
  initial_rotation: [-0.4843, 0.6818, 0.5482, -0.0115]
  initial_translation: [1.3001, 0.6882, 1.5745]


# Feature extraction parameter
ORB:
  num_features: 1000
  edge_threshold: 20
  patch_size: 25
  fast_threshold: 20
  min_keypoints_cell: 5
  feature_window: 80
  orb_iterations: 10
  fast_step: 5
  fast_lower_limit: 10
  fast_higher_limit: 80

# RANSAC for PnP
PnP:
  reprojection_window: 8
  ransac_iterations: 100
  confidence: 0.99

# Keyframe insertion
Keyframe:
  min_inliers: 50
  max_keyframes: 100

# Map filtering
Map:
  min_observations: 3
  max_depth_ratio: 1.5

Camera:
  K: 
    - [517.3, 0.0, 318.6]
    - [0.0, 516.5, 255.3]
    - [0.0, 0.0, 1.0]
  distortion: [0.2624,	-0.9531, -0.0054, 0.0026, 1.1633]