Tracker:
  reprojection_window: 15


# Feature extraction parameter
ORB:
  num_features: 1000
  edge_threshold: 31
  patch_size: 31
  fast_threshold: 20

# RANSAC for PnP
PnP:
  ransac_iterations: 1000
  reprojection_error: 2.0
  confidence: 0.99

# Keyframe insertion
Keyframe:
  min_inliers: 50
  max_keyframes: 100

# Map filtering
Map:
  min_observations: 3
  max_depth_ratio: 1.5

Camera:
  K: 
    - [517.3, 0.0, 318.6]
    - [0.0, 516.5, 255.3]
    - [0.0, 0.0, 1.0]
  distortion: [0.2624,	-0.9531, -0.0054, 0.0026, 1.1633]