# Feature extraction parameter
ORB:
  num_features: 1000
  edge_threshold: 0
  patch_size: 25
  min_keypoints_cell: 7
  split_size: 20
  orb_iterations: 10
  fast_threshold: 20
  fast_lower_limit: 7
  fast_higher_limit: 60
  fast_step: 5

# RANSAC for PnP
PnP:
  reprojection_window: 4
  ransac_iterations: 50
  confidence: 0.99

Matcher:
  orb_descriptor_value: 100
  window: 7
  minim_points_found: 20
  ratio_first_second_match: 0.70

Camera:
  K: 
    - [517.3, 0.0, 318.6]
    - [0.0, 516.5, 255.3]
    - [0.0, 0.0, 1.0]
  distortion: [0.2624,	-0.9531, -0.0054, 0.0026, 1.1633]