Tracker:
  # first is w, x, y, z similar with order in Eigen::Quaternion();
  # 0.6574 0.6126 -0.2949 -0.3248
  initial_rotation: [-0.4843, 0.6818, 0.5482, -0.0115]
  initial_translation: [1.3405, 0.6266, 1.6575]
  minim_points_found: 50


# Feature extraction parameter
ORB:
  num_features: 2000
  edge_threshold: 0
  patch_size: 25
  min_keypoints_cell: 10
  split_size: 20
  orb_iterations: 10
  fast_threshold: 25
  fast_lower_limit: 15
  fast_higher_limit: 60
  fast_step: 5

# RANSAC for PnP
PnP:
  reprojection_window: 4
  ransac_iterations: 50
  confidence: 0.99

Matcher:
  orb_descriptor_value: 50
  window: 4
  minim_points_found: 50
  ratio_first_second_match: 0.70

Camera:
  K: 
    - [517.3, 0.0, 318.6]
    - [0.0, 516.5, 255.3]
    - [0.0, 0.0, 1.0]
  distortion: [0.2624,	-0.9531, -0.0054, 0.0026, 1.1633]